In [8]:
import pandas as pd
import datetime as dt
from Date_compute import MMonthago,YMonthago 

def getdata():
    dfgl=pd.read_csv('https://covid.ourworldindata.org/data/owid-covid-data.csv')
    dfgl_date=dfgl['date'].str.split('-',5, True)
    dfgl['Y']=dfgl_date[0]
    dfgl['M']=dfgl_date[1]
    dfgl['D']=dfgl_date[2]
    return dfgl
def rowdataclean(dfgl):
    countrymapping=pd.read_excel(r'contry_mapping.xlsx')
    countrymapping=countrymapping.rename(columns={'English_name':'location'})
    dfgl1=pd.merge(dfgl,countrymapping,how='left')
    dfgl1.to_excel(r'myrawdata.xlsx',index=False)
    return dfgl1
def rawdata2month(rawdata,thisyear,thismonth):
    Ylist=YMonthago(thisyear,thismonth,3)
    Mlist=MMonthago(thismonth,3)
    mask1=rawdata['Y']==Ylist[0]
    mask2=rawdata['Y']==Ylist[1]
    mask3=rawdata['M']==Mlist[0]
    mask4=rawdata['M']==Mlist[1]
    rawdata2month=rawdata[(mask1&mask3)|(mask2&mask4)]
    return rawdata2month
def updaterawdatathis2month():
    now=dt.datetime.now()
    today=now.strftime('%Y_%m_%d')
    Y=int(now.strftime('%Y'))
    M=int(now.strftime('%m'))
    rawdata=pd.read_excel(r'myrawdata.xlsx')
    rawdata2monthdf=rawdata2month(rawdata,Y,M)
    rawdata2monthdf.to_excel(r'myrawdata2month.xlsx',index=False)
def fiternewcase(date,chinese_country):
    try:
        myrawdata2month=pd.read_excel(r'myrawdata2month.xlsx')
        #date='2021-08-18'
        #chinese_country='泰國'
        maskdata=myrawdata2month['date']==date
        maskcountry=myrawdata2month['Chinese_name']==chinese_country
        filterdata=myrawdata2month[(maskdata&maskcountry)]
        newcaseary=filterdata['new_cases'].values
        return newcaseary[0]
    except:
        return '錯誤,可能是資料還未更新或格式打錯嘍~!'

In [3]:
dfgl=getdata()
rowdataclean(dfgl)
updaterawdatathis2month()

In [7]:
fiternewcase('2021-08-18','泰國')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [17]:
rawdata=pd.read_excel(r'myrawdata.xlsx')
rawdata2monthdf=rawdata2month(rawdata,Y,M)
rawdata2monthdf.to_excel(r'myrawdata2month.xlsx')

,Unnamed: 0,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality,Y,M,D,Chinese_name
128,128,AFG,Asia,Afghanistan,2020-07-01,31826.0,319.0,303.000,780.0,28.0,...,NaN,37.746,0.5,64.83,0.511,NaN,2020,7,1,阿富汗
129,129,AFG,Asia,Afghanistan,2020-07-02,32012.0,186.0,263.857,809.0,29.0,...,NaN,37.746,0.5,64.83,0.511,NaN,2020,7,2,阿富汗
130,130,AFG,Asia,Afghanistan,2020-07-03,32314.0,302.0,267.571,821.0,12.0,...,NaN,37.746,0.5,64.83,0.511,NaN,2020,7,3,阿富汗
131,131,AFG,Asia,Afghanistan,2020-07-04,32662.0,348.0,293.714,828.0,7.0,...,NaN,37.746,0.5,64.83,0.511,NaN,2020,7,4,阿富汗
132,132,AFG,Asia,Afghanistan,2020-07-05,32941.0,279.0,283.429,866.0,38.0,...,NaN,37.746,0.5,64.83,0.511,NaN,2020,7,5,阿富汗
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110466,110466,ZWE,Africa,Zimbabwe,2021-08-14,119853.0,345.0,566.143,4090.0,17.0,...,30.7,36.791,1.7,61.49,0.571,NaN,2021,8,14,辛巴威
110467,110467,ZWE,Africa,Zimbabwe,2021-08-15,120088.0,235.0,537.286,4109.0,19.0,...,30.7,36.791,1.7,61.49,0.571,NaN,2021,8,15,辛巴威
110468,110468,ZWE,Africa,Zimbabwe,2021-08-16,120088.0,0.0,462.143,4109.0,0.0,...,30.7,36.791,1.7,61.49,0.571,NaN,2021,8,16,辛巴威
110469,110469,ZWE,Africa,Zimbabwe,2021-08-17,121046.0,958.0,541.143,4156.0,47.0,...,30.7,36.791,1.7,61.49,0.571,NaN,2021,8,17,辛巴威
110470,110470,ZWE,Africa,Zimbabwe,2021-08-18,121498.0,452.0,506.286,4181.0,25.0,...,30.7,36.791,1.7,61.49,0.571,NaN,2021,8,18,辛巴威

In [22]:
myrawdata2month=pd.read_excel(r'myrawdata2month.xlsx')
date='2021-08-18'
chinese_country='泰國'
maskdata=myrawdata2month['date']==date
maskcountry=myrawdata2month['Chinese_name']==chinese_country
filterdata=myrawdata2month[(maskdata&maskcountry)]
filterdata['new_cases']

50609    20515.0
Name: new_cases, dtype: float64

In [25]:
newcaseary=filterdata['new_cases'].values

In [26]:
newcaseary[0]

20515.0